library(tidyverse)

##relevant reference studies:
##Trueblood 2013 'not just for consumers':
## (stim generated by) a bivariate normal distribution in which the mean height was 50 pixels, the mean width was 80 pixels, and the variance in each  dimension was 2 pixels, with no correlation between variance in height and width.
##Black rectangles on white background, L-to-R line with jitter in height-of-placement, size unspecified, looks like up to 25px in the example.
##Unclear how far away decoys were! Can guess 5% ish from scatterplot presentation? spektor claims 10-16%, where did they get this number?

##spektor 2018 'repulsion effect'
##Triangle arrangement around center of screen (tested vs line in exp 4b)
##difficulty levels is for a TRUE difference between alternatives of 3%, 7% or 30% (catch trials). Target decoy distance is 2%, 5%, or 9% in exp1, exp2 adds a 14% level, and reports a main effect of distance (closer: more repulsion, further less repulstion, approaching indifference but not flipping to attration) 
##Rectangles are 230–270 pixels width, 150–190 pixels height
## Repulsion at shortest attribute distances (5%), attraction at largest distances (14%), dead-zone in between (9%). So this is the range to aim for?
## "When the options were arranged farther apart, the attraction effect disappeared entirely and even became a robust repulsion effect. But the stimulus design also played a crucial role: When individuals faced choice sets of varying difficulty and, more important, with varying attribute distances between the target and decoy, the repulsion effect became stronger or the attraction effect became weaker"

##SO: CURRENT DESIGN PITCH
##RF decoys only because decoy type is a distraction.
## 5,10,15% decoy distances (x5 shapeflavors, orientations randomized)
##attraction, similarity, and compromise effects.
##absolute sizes in the low three digit px range.


set.seed(4) #reproducible

##Convention: an option is a list(x,y), a triad is a list of three options.
get_decoy <- function(option,delta){
    return(
        list(
            x=sqrt(delta)*option$x,
            y=sqrt(delta)*option$y
        )#result: total area is multiplied by delta. If delta is .95, you get a decoy with a 5% reduction in area, reducing x and y by the same proportion. Woo.
    )
}
get_equivalue <- function(option,delta_x){
    delta_y = (option$x*option$y)/(option$x+delta_x)-option$y
    return(list(x=option$x+delta_x,y=option$y+delta_y)) #equal area, but x shifted by delta_x
}

get_target <- function(){
    return(
        list(x=1,y=.5)
        ##list(x=abs(rnorm(1,1,.1)),y=abs(rnorm(1,.5,.1)))
    )
}

get_clone <- function(anoption){
    return(
        list(x=anoption$x, y=anoption$y)
    )
}

get_competitor <- function(option){ #competitors are just flipped (rot90) targets.
    return (list(x=option$y,y=option$x))
}

##Convenient for R
triad_to_df <- function(atrial,shapeflavor,role, orientation, stimid,decoydist){
    return( data.frame(option1attribute1=atrial[[1]][["x"]],
                      option1attribute2=atrial[[1]][["y"]],
                      option2attribute1=atrial[[2]][["x"]],
                      option2attribute2=atrial[[2]][["y"]],
                      option3attribute1=atrial[[3]][["x"]],
                      option3attribute2=atrial[[3]][["y"]],
                      option1shape=shapeflavor[1],
                      option2shape=shapeflavor[2],
                      option3shape=shapeflavor[3],
                      option1orientation=orientation[1],
                      option2orientation=orientation[2],
                      option3orientation=orientation[3],
                      option1role=role[1],
                      option2role=role[2],
                      option3role=role[3],
                      stimid = stimid,
                      decoydist=decoydist
                      ))
}

##Convenient for stim display:
triad_to_js <- function(triad,shapetypes,roles,orientations,stimid,decoydist){
    ##js call is triangle(base,height,templatetype, orientation)
    ##    js.string <- "trialgetter(",triad[[1]]$x,",",triad[[1]$y,",",triad[[2]]$x,",",triad[[2]$y,",",triad[[3]]$x,",",triad[[3]$y,",[",roles,"]",",",stimid
    paste(paste0("trialgetter(",triad[[1]]$x),triad[[1]]$y,triad[[2]]$x,triad[[2]]$y,triad[[3]]$x,triad[[3]]$y,
          paste0("['",paste0(shapetypes,collapse="','"),"']",collapse=""),
          paste0("['",paste0(roles,collapse="','"),"']",collapse=""),
          paste0("['",paste0(orientations,collapse="','"),"']",collapse=""),
          paste0("'",stimid,"'"),
          paste0("'",decoydist,"')"),
          sep=",")
    
    ##orientation is 0,1,2,3 for NSEW (NS is tall, EW is wide, N has point up base down)
    ##templatetype is one of 'rightangle', 'equilateral', 'skew'.

}

##MAIN()
stimlist <- c()
##RF decoys only because decoy type is a distraction.
## 5,10,15% decoy distances (x5 shapeflavors, orientations randomized)
##attraction, similarity, and compromise effects.
##absolute sizes in the low three digit px range.

##attraction decoys
stimlist <- c()#write to demostim.txt as a js array -> human-viewable format
stim.df <- data.frame()#write to demostim.csv as a data frame -> stan friendly format

##Attraction/similarity trials:seems ok
for(decoydist in c(0.95,0.9,0.85)){#5,10,15% gap on decoys
    for(shapeflavor in list(c(0,0,0),c(0,0,1),c(0,1,0),c(1,0,0),c(0,1,2))){
        targ <-  get_target()
        decoy <- get_decoy(targ,decoydist)
        atrial <- list(targ,targ,decoy) #orientation determines which is targ and which is comp
        stimid=paste0("attraction",decoydist,"shapes",paste0(shapeflavor,collapse=""))
        
        stimlist <- append(stimlist,triad_to_js(atrial,shapeflavor,c("targ","comp","decoy"),c(0,1,0),stimid,decoydist))
        stim.df <- rbind(stim.df,triad_to_df(list(targ,get_competitor(targ),decoy),shapeflavor,c("targ","comp","decoy"),c(0,1,0),stimid,decoydist))#notice attributes here match 'NS' and 'EW', not base-and-height+orientation, which is how the js draws them. Beware confusion, the meaning of orientation has changed. This is not ideal...
    }
}

##Compromise/similarity trials
for(slidedist in c(-.025,-.05,-.1,-.15)){
    for(shapeflavor in list(c(0,0,0),c(0,0,1),c(0,1,0),c(1,0,0),c(0,1,2))){
        targ <- get_target()
        decoy <- get_equivalue(targ,slidedist)
        stimid=paste0("compromise",slidedist,"shapes",paste0(shapeflavor,collapse=""))
        stimlist <- append(stimlist,triad_to_js(list(targ,targ,decoy),shapeflavor,c("targ","comp","decoy"),c(0,1,0),stimid,slidedist))
        stim.df <- rbind(stim.df,triad_to_df(list(targ,get_competitor(targ),decoy),shapeflavor,c("targ","comp","decoy"),c(0,1,0),stimid,slidedist))#notice attributes here match 'NS' and 'EW', not base-and-height+orientation, which is how the js draws them. Beware confusion, the meaning of orientation has changed. This is not ideal...
    }
}

for(winnermargin in c(1.05, 1.1, 1.15)){
    for(shapeflavor in list(c(0,0,0),c(0,0,1),c(0,1,0),c(1,0,0),c(0,1,2))){
    targ <- get_target()
    decoy <- get_decoy(targ, winnermargin)
    atrial <- list(targ,targ,decoy)
    stimid=paste0("winner",winnermargin,"shapes",paste0(shapeflavor,collapse=""))
    stimlist <- append(stimlist,triad_to_js(atrial,shapeflavor,c("targ","comp","decoy"),c(0,1,0),stimid,winnermargin))
    stim.df <- rbind(stim.df,triad_to_df(list(targ,get_competitor(targ),decoy),shapeflavor,c("targ","comp","decoy"),c(0,1,0),stimid,winnermargin))
        }
    
    }
##Output
write(paste0("[",paste(stimlist,collapse=","),"]"),file="demostim.txt")
write.csv(stim.df,file="demostim.csv",row.names=FALSE)
